#!/usr/bin/env python3
from sys import stdin,argv

if len(argv)!= 2:
   print("Usage: cvt rotten-file")

n = int(argv[1])
lines = [l for l in stdin]
l = eval(lines[0])

for i in l:
    s23=bin(i)[2:][::-1]
    l = len(s23)
    s=''
    for j in range(n):
        if j >= l:
            s += '2'
        else:
            s += '3' if s23[j] == '1' else '2'
    print(s)
    
    
